"""Marketplace and plugin scaffolding."""

from __future__ import annotations

import shutil
from pathlib import Path

from guild._build import build_and_write

# ------------------------------------------------------------------
# Templates
# ------------------------------------------------------------------

_GUILD_TOML = """\
[marketplace]
name = "{name}"
owner = "{owner}"
{email_line}{description_line}"""

_PLUGIN_TOML = """\
[plugin]
name = "{name}"
version = "0.1.0"
description = "{description}"
"""

_PLUGIN_CLAUDE_MD = """\
# {name}

Instructions for Claude when this plugin is active.

## What this plugin does

<!-- Describe the plugin's purpose -->

## When to use

<!-- Describe when Claude should apply this plugin -->

## Constraints

<!-- Any rules or limitations -->
"""

_VALIDATE_WORKFLOW = """\
name: Validate

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install jaymd96-guild
      - run: guild validate
"""

_RELEASE_WORKFLOW = """\
name: Release

on:
  push:
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install jaymd96-guild
      - run: guild validate
      - name: Create Release
        uses: softprops/action-gh-release@v2
"""

_GITIGNORE = """\
# guild build artifacts — regenerated by `guild build`
marketplace.json
"""


# ------------------------------------------------------------------
# Scaffolding functions
# ------------------------------------------------------------------


def init_marketplace(
    path: Path,
    *,
    name: str | None = None,
    owner: str = "",
    email: str | None = None,
    description: str | None = None,
) -> Path:
    """Scaffold a new marketplace at *path*.

    Creates ``guild.toml``, ``plugins/``, CI workflows, and runs an
    initial build to generate ``marketplace.json``.

    Returns the path to the created marketplace.
    """
    path = path.resolve()
    path.mkdir(parents=True, exist_ok=True)

    if name is None:
        name = path.name

    # guild.toml
    email_line = f'owner_email = "{email}"\n' if email else ""
    description_line = f'description = "{description}"\n' if description else ""
    (path / "guild.toml").write_text(
        _GUILD_TOML.format(
            name=name,
            owner=owner,
            email_line=email_line,
            description_line=description_line,
        )
    )

    # plugins/
    (path / "plugins").mkdir(exist_ok=True)

    # README.md
    (path / "README.md").write_text(f"# {name}\n\nA Claude Code plugin marketplace.\n")

    # .gitignore
    (path / ".gitignore").write_text(_GITIGNORE)

    # CI workflows
    workflows = path / ".github" / "workflows"
    workflows.mkdir(parents=True, exist_ok=True)
    (workflows / "validate.yml").write_text(_VALIDATE_WORKFLOW)
    (workflows / "release.yml").write_text(_RELEASE_WORKFLOW)

    # Initial build
    build_and_write(path)

    return path


def add_plugin(
    workspace: Path,
    name: str,
    *,
    description: str = "",
) -> Path:
    """Scaffold a new local plugin under ``plugins/<name>/``.

    Creates ``plugin.toml``, ``CLAUDE.md``, and ``skills/`` directory.
    Returns the path to the created plugin directory.
    """
    plugin_dir = workspace / "plugins" / name
    if plugin_dir.exists():
        msg = f"Plugin directory already exists: {plugin_dir}"
        raise FileExistsError(msg)

    plugin_dir.mkdir(parents=True)

    # plugin.toml
    (plugin_dir / "plugin.toml").write_text(_PLUGIN_TOML.format(name=name, description=description))

    # CLAUDE.md
    (plugin_dir / "CLAUDE.md").write_text(_PLUGIN_CLAUDE_MD.format(name=name))

    # skills/
    (plugin_dir / "skills").mkdir()

    return plugin_dir


def remove_plugin(workspace: Path, name: str) -> bool:
    """Remove a local plugin directory.

    Returns True if the plugin was found and removed, False if not found.
    Does not modify ``guild.toml`` — external sources must be removed
    by editing that file directly.
    """
    plugin_dir = workspace / "plugins" / name
    if plugin_dir.is_dir():
        shutil.rmtree(plugin_dir)
        return True
    return False
